### ISSUE TITLE
Entity Validation Fails

### ISSUE THREAD

**Issue by BelAirIT** [NewSpring/Excavator#110]
I've got an Individual.csv that Excavator accepts and makes it almost all the way through the import process.  Right after the import starts, checks the database for duplicates and starts individual imports the following message pops up.

![capture](https://cloud.githubusercontent.com/assets/7409839/5668942/693961ba-9728-11e4-85c0-eeb04b72e636.PNG)

I figured there must be something wrong with my data so after using the sample file as a template I added a single user which fails.  Even adding the bare minimum of a family id and person id and nothing else it still fails.

Here's the file I'm using: http://www.filedropper.com/individual

**Comment by BelAirIT** [comment]
While this is still happening I've used a workaround to keep going.  If I use a record from the sample file as the first row it accepts my data.

**Comment by dcs619** [comment]
Sorry, I haven't had a chance to look at this yet.  Your filedropper link
didn't work.

David Stevens

*Web Developer*NewSpring Church
www.newspring.cc
864-965-9540

**Comment by dcs619** [comment]
@BelAirIT Can you upload that file to Dropbox?

**Comment by BelAirIT** [comment]
https://www.dropbox.com/s/7qjxr6zeh8mxawm/Individual.csv?dl=0
