### ISSUE TITLE
F1: Update IsValidEmail Regex

### ISSUE THREAD

**Issue by bwitting** [NewSpring/Excavator#112]
I'm working on tracking down an DbEntityValidationException when trying to import emails (Communications).  I surrounded `lookupContext.SaveChanges(DisableAudit);` in Communications.cs with a Try/Catch, and figured out the problem - someone has been storing emails in our F1 database as 2 emails separated by a ; (I guess to get 2 emails in the one field?!?) like email1@domain.com;email2@domain.com.  I suck at Regex and couldn't figure out how to update IsValidEmail, so I did this instead: `if ( value.IsValidEmail() & !value.Contains(";"))`

This is probably a isolated incident, but I wanted to let you know in case you wanted to update the IsValidEmail Regex to not be valid if a ; is present. (just in case someone else figures you can sneak 2 emails in one email field with a semicolon!)

**Comment by ElimAdmin** [comment]
Be assured: this is NOT an isolated incident!  We ran into this with the uploading of our data using CSV as well.  We also had some other invalid characters in email addresses.

**Comment by dcs619** [comment]
IsValidEmail is a core Rock method that should probably be updated if you want to create an issue there.
https://github.com/SparkDevNetwork/Rock/blob/develop/Rock/Utility/ExtensionMethods.cs#L1093

When we imported our database, that core method allowed "www" and "http" in email addresses so I modified it...I will fix it in Excavator.

**Comment by dcs619** [comment]
@bwitting The current regex will work, I just forgot to close the end so that additional characters/email are invalid.
