### ISSUE TITLE
F1: Phone Numbers importing multiple times / incorrectly

### ISSUE THREAD

**Issue by bwitting** [NewSpring/Excavator#113]
@dcs619  When importing communications values from F1, phone numbers are not working as expected.  Sometimes, numbers that exist in F1 are not imported at all. Other times, the same number is imported over and over for a singe person:  

![e1](https://cloud.githubusercontent.com/assets/1859094/6045438/219e7d0e-ac68-11e4-98ca-94274f158a40.png)

Here's this individual's phone numbers in the (Rock) database:

![e2](https://cloud.githubusercontent.com/assets/1859094/6045455/391a8bc6-ac68-11e4-961e-016f7238136a.png)

In F1, this person has multiple phone numbers. But the only thing Excavator imported was the household phone number (and 10 times)

![e3](https://cloud.githubusercontent.com/assets/1859094/6045471/5446fc5e-ac68-11e4-97ba-1249d7abefa9.png)

**Comment by bwitting** [comment]
I seemed to "solve" this issue by importing only individuals/households, then importing only communications.  Then all numbers were imported and the duplicated didn't happen.

**Comment by dcs619** [comment]
Fixed in 4a668c2e6d9f101468220cc26cb2cf4193a715b8
