### ISSUE TITLE
Error when clicking "Upload" & "SQL Authentication"

### ISSUE THREAD

**Issue by jadtaylor** [NewSpring/Excavator#114]
When clicking "Upload" an error immediately pops up stating, "Excavator has stopped working."

Clicking "Connect" brings up the server dialog and allows input of Server and Database. The same error as previously described occurs when selecting "SQL Authentication."

Also, there is no option to choose "CSV Upload" from the start screen.

Any help would be greatly appreciated! Thanks to the community in advance.

![rock rms start](https://cloud.githubusercontent.com/assets/6354794/6491727/42640ede-c27d-11e4-92f7-49fe1e7df28c.png)
![rock rms error](https://cloud.githubusercontent.com/assets/6354794/6491734/46394aba-c27d-11e4-81f7-0ba19a5e5a5c.png)

**Comment by dcs619** [comment]
This is related to #111, Windows is blocking the embedded files from loading.

Can you try the following:
Right click folder, Properties and uncheck Read Only
Right click folder, Properties, click "unblock" option
Right click Excavator.exe and run as administrator

**Comment by jadtaylor** [comment]
Yes. This worked perfectly. I had to unblock each file individually as Windows 7 did not give the option to unblock all files from the folder properties.

Thank you! Sorry for the duplicate issue. I tried to search thoroughly for a related issue and missed the one right in front of my nose.
