### ISSUE TITLE
CSV: No Way to Set Phone Country Code

### ISSUE THREAD

**Issue by arranf** [NewSpring/Excavator#117]

**Comment by arranf** [comment]
Note for those using Excavator in the meantime until this issue is resolved. This SQL will set the country code to +44 (UK) for all the people in your DB. 

```
UPDATE [rock].[dbo].[PhoneNumber]
SET CountryCode=44
```

**Comment by arranf** [comment]
For those who stumble across this who are based in the UK. 
Excavator doesn't have the ability to set regex on your numbers and so your leading 0s won't get stripped off which can cause issues with SMS down the road.

If you use the following SQL query this will fix that

`
UPDATE [rock].[dbo].[PhoneNumber]
SET Number = RIGHT(Number, LEN(Number) - 1)
WHERE NumberTypeValueId='12' AND Number LIKE '0%'
`

**Comment by dcs619** [comment]
Good to know, thanks.  I haven't updated the CSV section for 3.2 yet but I planned on fixing this during the update.
