### ISSUE TITLE
1.3: Crashes on Connect Button Press [Windows 7 Professional & Windows Server 2012]

### ISSUE THREAD

**Issue by arranf** [NewSpring/Excavator#119]
Regardless of the values in Excavator.exe.config (my own or the default) every time I click the connect button a message pops up saying Excavator has stopped working.

I've tried running in compatibility mode and as administrator.

**Comment by arranf** [comment]
I used develop as a base branch and merged in commits 1d5d288d66a2594595073dd12a8ad934eb19ffa8 and e2458eed556554251bb53df82b75aef24015914d and I was able to connect successfully.

**Comment by dcs619** [comment]
@arranf Are you on the alpha 1.3 release?  Since they've been adding a ton of things (up to 1.3.1) the current develop/master branch only supports 1.2.

**Comment by arranf** [comment]
Sorry I might've been unclear.

Because I was running intro trouble with 1.3 on Windows 7 I thought it
might've been to do with some of the dependency changed you committed. What
I did with my fork was I took the develop branch and then merged in your
1.3 specific changes and I got that to run fine.

I'm running the 1.3 BETA (so not on 1.3.1).

On 9 April 2015 at 13:59, David Stevens <notifications@github.com> wrote:

> @arranf <https://github.com/arranf> Are you on the alpha 1.3 release?
> Since they've been adding a ton of things (up to 1.3.1) the current
> develop/master branch only supports 1.2.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NewSpring/Excavator/issues/119#issuecomment-91223486>.
>



-- 
*​​Arran France*
​​
Communications, Youth Work, and Administration
​
*​T.* 07425 159471​

​
*​Hope Church Corby*
Registered
​ UK​
 Charity
​ ​
251549​
*​*
The Hope Centre
8 Princewood Road
Corby
NN17
​4
AP

**Comment by dcs619** [comment]
Gotcha

**Comment by arranf** [comment]
You can see the build I've been using instead [here](https://github.com/arranf/Excavator/tree/develop).

**Comment by dcs619** [comment]
I'm able to reproduce this on Server 2012 R2 using Rock 1.3.2.  

For now you'll have to edit your .config file manually to set the connection to the database.

**Comment by arranf** [comment]
@dcs619 I've imported so this isn't an issue for me now. When I was experiencing this problem I did edit the .config file but I wasn't able to connect as pressing the button crashed the program despite the connection string being there already.

**Comment by dcs619** [comment]
If you edit the config file, there's no reason to click the Connect
button.  The connect button is just there for people who are afraid to edit
files in notepad :)

**Comment by JayGreentree** [comment]
I am having this issue on Windows 7 Home edition. Should I upgrade my OS to 7 Professional?

**Comment by dcs619** [comment]
Have you tried right clicking the executable and unblocking the file? If
that doesn't work you should edit the config file manually.

You don't have to click the Connect button during import: it's just there
to help set the config file.

**Comment by JayGreentree** [comment]
I have edited the file and tried running as Administrator

**Comment by dcs619** [comment]
If you edit the config file, you don't need to click Connect.  Does it
crash somewhere else?

David Stevens

*Web Developer*NewSpring Church
www.newspring.cc
864-965-9540

**Comment by JayGreentree** [comment]
It crashes on either button with or without the edited config file. This is what I get on upload or connect
![rockerror](https://cloud.githubusercontent.com/assets/215971/8048534/a4761510-0e20-11e5-9872-c21508b61bcc.png)

**Comment by dcs619** [comment]
Windows is still blocking the files, otherwise that yellow bar across the top would be transparent with the current page title:

![image](https://cloud.githubusercontent.com/assets/1210933/8048628/1afa71b2-0e22-11e5-90b3-93dc7d87462c.png)

When you download Excavator, right click the ZIP and choose Properties.  Click Unblock, then extract the files.

**Comment by JayGreentree** [comment]
Awesome thats something I had not known about apparently. Wish I had known about that trick a while back our church could have gone public with Rock months ago.

**Comment by dcs619** [comment]
This is confirmed working in the develop branch (which also includes updates to support v4.0).  However, until 4.0 comes out I won't merge that to master.
