### ISSUE TITLE
Is importing an Excel file into the Rock Possible?

### ISSUE THREAD

**Issue by bacsrlette** [NewSpring/Excavator#127]
Hello. We recently completed an import of F1 data using Excavator for a church. The church has also given us an additional Excel file of contact records. How can Excel file data be imported into the Rock?

**Comment by dcs619** [comment]
@bacsrlette You can save the Excel file as a CSV then import it.  You'll need to follow the formatting conventions listed in the [wiki](https://github.com/NewSpring/Excavator/wiki/3.-CSV-Import).
