### ISSUE TITLE
ArgumentNullException on .ShowDialog() in btnConnect_Click

### ISSUE THREAD

**Issue by bradbamford** [NewSpring/Excavator#136]
Running Excavator on a Windows 10 box is crashing on btnConnect_Click ( orange Connect button) .
It's getting 

An unhandled exception of type 'System.ArgumentNullException' occurred in PresentationFramework.dll 
in ConnectPage.xaml.cs line 363

var windowConnected = connectWindow.ShowDialog() ?? false;

I don't have a lot of experience with WPF, any ideas why .ShowDialog() would be causing an ArgumentNullException?

**Comment by bperreault** [comment]
Hi, bradbamford
Have you checked for valid connection string in the configuration file?

**Comment by bradbamford** [comment]
Does it have to have a valid connection string before running the app?

I've tried with the default one first (Excavator.exe.config and App.config when running from VS2015), assuming I could edit connection string settings from within the app. 

I have also tried replacing the connection string in the config files with the same Connection String I'm running Rock, as found in web.ConnectionStrings.config

**Comment by bperreault** [comment]
Last I knew, the connection string needs set up first. Also , try running it as administrator. In case there's an access issue with the location of the db. For example I would avoid trying to use any db located on your desktop. But David will have more wisdom than I.


Sent from my T-Mobile 4G LTE Device-------- Original message --------From: bradbamford <notifications@github.com> Date: 1/16/2016  5:40 PM  (GMT-05:00) To: NewSpring/Excavator <Excavator@noreply.github.com> Cc: Bobbi Perreault <bcp@faxt.com> Subject: Re: [Excavator] ArgumentNullException on .ShowDialog() in
  btnConnect_Click (#136) 
Does it have to have a valid connection string before running the app?

I've tried with the default one first (Excavator.exe.config and App.config when running from VS2015), assuming I could edit connection string settings from within the app. 

I have also tried replacing the connection string in the config files with the same Connection String I'm running Rock, as found in web.ConnectionStrings.config

**Comment by dcs619** [comment]
@bradbamford If you've set up the connection string in the config file, you don't need to use the Connect button within the app.  The Connect button is there for non-power users :smile: 

I've fixed this issue in the latest build, but it also has Rock v4 code in it so I'm waiting on that to be released before I can make it the default download.  See #119.

**Comment by bradbamford** [comment]
Thanks @dcs619 for the explanation and link to the closed issue.

**Comment by dcs619** [comment]
Excavator has been updated to support Rock 1.4.1.

**Comment by islandross** [comment]
Confirmed to be working. Thank you so much.
