### ISSUE TITLE
System.Data.SqlClient.SqlException: Invalid column name 'SourcesTypeId'

### ISSUE THREAD

**Issue by islandross** [NewSpring/Excavator#138]
Trying to use Excavator running Rock.dll 1.3.4 with a new Rock 4.1 install. Simply testing with the sample Indviduals.csv will produce a SQL error System.Data.SqlClient.SqlException: Invalid column name 'SourcesTypeId' .

Just wondering if we have to wait for an Excavator update before we can use it for Rock 4.1. as some other forums posts response says that Excavator 1.3.4 should work with 4.0.

Many Thanks

**Comment by dcs619** [comment]
Hey Ross, I have a build for v4 staged in the develop branch.  I'll be pushing it to master as soon as I test with 4.1 to ensure there are no breaking changes.

**Comment by dcs619** [comment]
Excavator has been updated to 4.1
