### ISSUE TITLE
CSV: The Leading Zero in Phone Numbers are dropped

### ISSUE THREAD

**Issue by leehockhin** [NewSpring/Excavator#152]
In Malaysia, most of the phone numbers start with Zero (Zone codes, e.g. 05, are necessary especially when calling from a mobile phone).

Excavator seems to be dropping the leading zero from my phone numbers.
Note: This looks like quite the opposite to the requirement in Issue #117 CSV: No Way to Set Phone Country Code

Please refer to the attached pdf file for details of the problem. Thanks
[Issues to report on Excavator Part 1.pdf](https://github.com/NewSpring/Excavator/files/245316/Issues.to.report.on.Excavator.Part.1.pdf)

**Comment by arranf** [comment]
Leehockhin, thus is probably due to your regex setup in Rock as opposed to
Excavator. Have you cong inured country specific regex?

**Comment by leehockhin** [comment]
Hi Arranf,
1)  Phone Country Code Regex is all new to me.  I could not find much information in the Rock Manuals.  Can you please direct me to documentation/notes on how to setup the Phone Country Codes in Rock?

2) How does Rock decide on the default Country Code for Phones?

**Comment by arranf** [comment]
@leehockhin I intend to do a short blog post showing how to configure Rock for international usage tomorrow evening (03/05/16 UK time). I'll cover that there.

**Comment by leehockhin** [comment]
Hi Arran France,
If you have done the blog, can you please provide the url ?

**Comment by leehockhin** [comment]
I have setup my country specific regex; used the latest Excavator available BUT, excavator is still dropping the leading Zero from my Phone number.

The phone number is fine if I manually add back the missing leading Zero

**Comment by arranf** [comment]
@leehockhin http://www.rockrms.com/Rock/BookContent/9/64#internationalizationlocalization Rock already has great documentation on that stuff so turns out I'd be duplicating.

**Comment by leehockhin** [comment]
Thanks Arran.  I didn't find this when I googled. Guess I didn't use the
right words.

**Comment by arranf** [comment]
@leehockhin Not everything is necessarily easy to find via Google. Asking in the Rock RMS Q&A is a good place to do it and so is joining the Slack channel

**Comment by leehockhin** [comment]
Thanks Arran.
Have a blessed day!

**Comment by leehockhin** [comment]
Summary: 
After a better understanding of Internationalization, setting up of regex codes, etc the problem with Excavator dropping the leading zero (did not test with more than one leading zero) still remains.  Whilst I can perform work-arounds, I think Excavator should only remove non-numeric characters as (1) the input data on CSV is a string type and (2) the field dbo.PhoneNumber.Number (nvarchar) also supports leading zeros.

**Comment by arranf** [comment]
Looks like it's this https://github.com/NewSpring/Excavator/blob/master/Excavator.CSV/Maps/Individual.cs#L350

**Comment by arranf** [comment]
@leehockhin If you've already imported I can provide you with SQL to fix this. Am I right in thinking you're just testing?

**Comment by leehockhin** [comment]
@arranf Yes, I am still doing some trial runs.  Most of the phone numbers I have in the csv file are like this
![screenshot of phone number in csv file](https://cloud.githubusercontent.com/assets/17799991/15097064/e94ba5ae-1542-11e6-86da-2da29c2f65ff.PNG)
Thus I think the code used is
![code line used](https://cloud.githubusercontent.com/assets/17799991/15097076/3b609566-1543-11e6-8e5e-9d2f19386012.PNG)
The code evaluates phone numbers to a numeric value, so leading zeros will be dropped.

My workaround (in case I have overseas numbers with extra zeros, numbers not starting with Zero, etc)
1) Append a 9 in front of all my phone numbers
2) Import using Excavator
3) Remove the first digit of all my phone numbers using SQL

**Comment by dcs619** [comment]
@leehockhin I've requested some time to look at this next week.  The code @arranf posted would definitely prevent leading zeros from being added.

**Comment by leehockhin** [comment]
@dcs619 any updates on this?

**Comment by treyhendon** [comment]
@leehockhin  is the "05" the Country Code in Rock?  I'm wondering if it's the .AsNumeric() that's stripping the leading zero for the Country.

**Comment by arranf** [comment]
@treyhendon, country codes don't come by default in Rock. The line of code
that's an issue is highlighted by me a little further up.

**Comment by knolly42** [comment]
Hi 

Looks like this issue is still alive?

I can see from my CSV the zero is there on the 3 x phone numbers in my single row CSV test file.

Post import, I can also see in SQL Server that the leading zero is missing on all three numbers, even though the regex is in place on the new install?

I can run the update SQL post import to correct this, but thought I'd let you know it is still an issue at least for UK numbers with a leading '0'.

Thanks
