### ISSUE TITLE
CSV: Hit Error during Family Import stage

### ISSUE THREAD

**Issue by leehockhin** [NewSpring/Excavator#153]
Hit this error (see attached log) during Family Import stage.
It could be due to my data, but it would be a good opportunity to debug.
[ExcavatorExceptions.txt](https://github.com/NewSpring/Excavator/files/251580/ExcavatorExceptions.txt)
![screenshot of excavator run](https://cloud.githubusercontent.com/assets/17799991/15065271/6de9dc0e-1390-11e6-911f-7f7db3f2f691.PNG)
Data imported is usable

**Comment by leehockhin** [comment]
When I re-run the Data Import with ReportingNumber = 5, the error came up earlier, and fewer records had valid Addresses (which I believe is from the Family Import section of the run)

**Comment by leehockhin** [comment]
When I rerun with ReportingNumber=500, the run was successful, with no error reported!
![screenshot excavator good run 500](https://cloud.githubusercontent.com/assets/17799991/15067055/36cfbcba-13a0-11e6-8c6e-ca08668f6266.PNG)
*** Notice the number of "progress dots" is less for this run with ReportingNumber=500

**Comment by dcs619** [comment]
@leehockhin What version of Rock are you running against?  It sounds like the ReportingNumber reached the middle of a family and then saved.

Also the number of dots is determined by 10% of your ReportingNumber, so that's why there's less.

**Comment by leehockhin** [comment]
I am now at "Rock McKinley 4.4"
And Excavator is using "Rock.dll v1.4.3.0"

**Comment by treyhendon** [comment]
@leehockhin  Have you completed your migration?  A recent pull request changed the way the Individual.csv file saves the families as it's parsing (to make sure there are not family members that cross the ReportingNumber in their row positions).  I wonder if you would have the same problem using the newest pull.
