### ISSUE TITLE
Custom Person Connection Status

### ISSUE THREAD

**Issue by BEGamache** [NewSpring/Excavator#154]
I noticed in People.cs the customConnectionType condition wasn't getting the correct status Id because the memberStatus variable was lowercase and the dv.Value wasn't (assuming Defined Values are uppercase). dv.Value.ToLower() will correct this.

// Lookup others that may be user-defined
var customConnectionType = connectionStatusTypes.Where( dv => dv.Value.ToLower() == memberStatus )
.Select( dv => (int?)dv.Id ).FirstOrDefault();

**Comment by dcs619** [comment]
@BEGamache good catch!
