### ISSUE TITLE
F1 Import - totally lost

### ISSUE THREAD

**Issue by imajprop** [NewSpring/Excavator#155]
I have been challenged by staff to convert all data in F1 to Rock and I need help. I have downloaded Excavator and unblocked each of its files from Windows. I have received a mdf file and 29 csv files from F1. When I run Excavator and choose the appropriate mdf file, I get confirmation stating "Successfully read import file" and then when connecting, I get "Successfully connected to Rock Database. All good so far! The next screen says "Unable to Load Preview or No Data Exists". Note that my mdf file is in excess of 11Mb so I assume there is data. I click Next and proceed anyways... on the following screen I get... "Starting Health Checks" and then an Exception stating "Network Path was not found"  Can you please tell me where I went wrong??

**Comment by dcs619** [comment]
Hey @imajprop, if you're getting No Preview that means Excavator wasn't able to read the F1 database.  The network path not found sounds like a connection issue, although I'm not sure what for.  There's a #migration channel in the Rock Slack that may be able to help you troubleshoot: http://rockrms.com/slack
