### ISSUE TITLE
Import Failed - No Logs

### ISSUE THREAD

**Issue by genchuba** [NewSpring/Excavator#164]
Hi Guys,

I am trying to import a CSV file to my Rock DB. DB connection is OK and File has been read OK. 
![image](https://cloud.githubusercontent.com/assets/14154313/21965908/1751ec9a-dbce-11e6-9b3e-6415fb1d7143.png)

Import preview doesn't show anything - just blank. 
![image](https://cloud.githubusercontent.com/assets/14154313/21965911/1ae3b1e0-dbce-11e6-871d-2112a877a967.png)

Wh I ran the import I get import failed error and no logs created.

8:23:02 PM  Starting health checks...
8:23:11 PM  Checking for existing people...
8:23:11 PM  Starting data import...
8:23:11 PM  Completed import: 0 rows processed.
8:23:11 PM  Could not finish upload. Check the exceptions log for details.

![image](https://cloud.githubusercontent.com/assets/14154313/21965914/1f60c44c-dbce-11e6-82da-706d58e48f7c.png)

Are you able to guide me on this? Thanks.

Rock Version: Rock McKinley 6.1
SQL Server: SQL 2012 Express on an Azure VM 2012R2
CSV file from: PCO, (formatted as per excavator instruction format)

**Comment by genchuba** [comment]
Rock Version: Rock McKinley 6.1
SQL Server: SQL 2012 Express on an Azure VM 2012R2
CSV file from: PCO, (formatted as per excavator instruction format)

**Comment by dcs619** [comment]
Hi @genchuba, it sounds like the CSV importer couldn't read the headers on your files.  

You may want to verify the CSV is formatted correctly using a site like [flat-file.net](http://flat-file.net).
