### ISSUE TITLE
 Index was outside the bounds of the array.

### ISSUE THREAD

**Issue by sm7urw** [NewSpring/Excavator#167]
Hi!

Thanks for a great tool. I get the following error while trying to import Family.cvs:

2017-02-10 13:13:40,Transform Data,"System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Excavator.CSV.CSVComponent.LoadFamily(CSVInstance csvData)
   at Excavator.CSV.CSVComponent.TransformData(Dictionary`2 settings)
   at Excavator.ProgressPage.bwImportData_DoWork(Object sender, DoWorkEventArgs e)"

Whats the problem with my data?

God bless,

// Henrik

**Comment by dcs619** [comment]
Hey Henrik, thanks for sharing.  You may want to verify the CSV is formatted correctly, usually that error signifies there is a unquoted comma somewhere.  Something like [flat-file.net](http://flat-file.net/) should point you in the right direction.

**Comment by sm7urw** [comment]
Hey and thanks dcs619!

**Comment by dcs619** [comment]
It sounds like there's a required field that's missing, but I can't tell from the error what it might be.  Did you start with the [sample CSVs](https://github.com/NewSpring/Excavator/tree/master/Excavator.CSV/SampleCSVs) to build your data file?

**Comment by sm7urw** [comment]
I've tried both importing the sample file and used that file to start building my own data file. Neither works.

**Comment by dcs619** [comment]
Ok, I'll take a look at the sample CSV file.

**Comment by sm7urw** [comment]
I managed to solve it somehow. Not sure what I did but I think the reason might be that I previously had changed fields such as Gender and Marital status to work with our language. Now it works great!

Thanks!
