### ISSUE TITLE
CSV file 

### ISSUE THREAD

**Issue by magdihanna** [NewSpring/Excavator#170]
Running for the first time for a new installed database .. 
System.ComponentModel.Win32Exception  (0x80004005): The system cannot find the file specified

**Comment by dcs619** [comment]
Thanks @magdihanna. The error sounds like a Windows issue.   Did you try unblocking the app as specified [here](https://github.com/NewSpring/Excavator#does-excavator-crash-after-opening-or-trying-to-use-it)?

**Comment by magdihanna** [comment]
Thanks for reply .. Yes I did that before starting . .

**Comment by magdihanna** [comment]
It is resolved . . THANKS

**Comment by jmccoolcaz** [comment]
How did you resolve this issue? I'm having the same issue and I have ublocked all files in the app. Thanks!

**Comment by magdihanna** [comment]
GA,
The database location was not correct on my case so after I did it it was OK . .


------------------------

Best Regards




Magdi Hanna





On Sunday, April 30, 2017, 7:36:00 AM GMT+4, jmccoolcaz <notifications@github.com> wrote:
How did you resolve this issue? I'm having the same issue and I have ublocked all files in the app. Thanks!
