### ISSUE TITLE
Individuals Import Fail after 1,918 records

### ISSUE THREAD

**Issue by knolly42** [NewSpring/Excavator#171]
Family import was perfect, but Individuals bombs with this:

15/05/2017 17:47:06,Transform Data,"System.Data.Entity.Validation.DbEntityValidationException: Validation failed for one or more entities. See 'EntityValidationErrors' property for more details.
   at System.Data.Entity.Internal.InternalContext.SaveChanges()
   at Rock.Data.DbContext.SaveChanges(Boolean disablePrePostProcessing)"

Any idea what it could mean please?

Also for some reason, the import is missing random data on a couple of person attributes? they show on a few people then drop out..

Hope you can shed some light on this please?

thanks

**Comment by dcs619** [comment]
@knolly42 I just released an update that should provide more detail for Entity Validation Errors.  Can you try it again and post the results?

**Comment by dcs619** [comment]
Released a fix for custom attributes. Also added additional date handling in case Excel screws up the formatting.
