### ISSUE TITLE
Fellowshipone Import Errors - "NO Imported People Exist"

### ISSUE THREAD

**Issue by desertSparrow** [NewSpring/Excavator#172]
Neet a little help. Installed the Excavator to a Windows 10 computer on the network. have the Excavator extracted on the Downloads folder. RUN the Excavator put in the connection info for the SQL Server and get all green lights.  

After less than a minuet I get the Error " No Imported People Exist" I'll attach screen shots. Please help. 
<img width="735" alt="screen shot 2017-06-09 at 7 16 16 pm" src="https://user-images.githubusercontent.com/29326627/27006227-7c94681c-4de3-11e7-951f-23858921d84a.png">
<img width="746" alt="screen shot 2017-06-06 at 11 09 49 am" src="https://user-images.githubusercontent.com/29326627/27006228-7cad7514-4de3-11e7-92a3-8b79709a3d07.png">

**Comment by tedinedh** [comment]
I am getting this exact same error. Import from F1 .mdf file. Same exact situation. Any help please?
