### ISSUE TITLE
Sample CSV files inaccessible

### ISSUE THREAD

**Issue by ElimAdmin** [NewSpring/Excavator#175]
Hi @dcs619.  The sample CSV files on the page https://github.com/NewSpring/Excavator/wiki/3.-CSV-Import are not accessible.  Is there a problem?  Does CSV import no longer work?  Is the format of the files being changed to cater for later versions?  What version should be used for import?  Thanks.
Refer https://www.rockrms.com/page/278?question=1622

**Comment by ElimAdmin** [comment]
@dcs619 @treyhendon @arranf
It looks like the location of the CSV sample files have been moved to Excavator.CSV/SampleCSVs/Contribution.csv etc, but the links on the CSV Wiki page haven't been updated.

Is there other content on this wiki page that also needs to be updated?

**Comment by dcs619** [comment]
Links in wiki have been updated.
