### ISSUE TITLE
Print issues on first press

### ISSUE THREAD

**Issue by mr9802** [NewSpring/Excavator#179]
Having an issue with the print all button when checking kids or volunteers in.  

Issue 1 - You have to hit the button 2 times to print all the labels.  The first press puts the Check Mark next to the person and the second prints the label.  https://Divine.tinytake.com/sf/MTc1OTQ4OV81NzgwMzcz

Issue 2 - When trying to print the individual label print it will print all the labels. https://Divine.tinytake.com/sf/MTc1OTQ5NF81NzgwMzc4

Background: Site started with checkin v1 on Rock v5.3 and am now updated to checkin v1.1 and Rock v6.6.  Also using the checkin app on a windows pc.

We are able to print correctly with a different Rock setup.  Used a test site and was able to print correctly on first press like expected.  

Thoughts?

**Comment by dcs619** [comment]
Closing, wrong repo
