### ISSUE TITLE
CSV Attributes Will Not Have Category and Never Match

### ISSUE THREAD

**Issue by treyhendon** [NewSpring/Excavator#184]
Wonder if there needs to add a `IsCSV` bool to the overloads and let that assist the matching logic since Excavator CSV will not have Attribute Category (or existing Attributes could be added/moved to multiple categories).

https://github.com/NewSpring/Excavator/blob/master/Excavator.Utility/AddMethods.cs#L670

**Comment by dcs619** [comment]
Included Attributes in the latest matching logic
