### ISSUE TITLE
F1: Visitor received household contact info instead of the family receiving it

### ISSUE THREAD

**Issue by BEGamache** [NewSpring/Excavator#51]
Noticed one of my visitors under my account received my previous and current addresses and they were not applied to my person profile. Not sure why it applied to the visitor and not the person who invited them.

Looked at a few other records and the family is not receiving the household address; only one of the visitors are receiving that family's address.

Looks like the visitor that receives the address is also receiving that family's contributions (if individual Id is left null in F1)

Also noticed for the visitor, the household contact info is being applied to this one visitor and not the actual household (they are receiving the address, household home phone, household contributions).

**Comment by dcs619** [comment]
Fixed in 4a668c2e6d9f101468220cc26cb2cf4193a715b8
