### ISSUE TITLE
F1: Visitors in F1 household are receiving Known Relationship to other visitors in that household.

### ISSUE THREAD

**Issue by BEGamache** [NewSpring/Excavator#52]
Visitors in F1 household are receiving Known Relationship to other visitors in that household (known relationship is set as invited). Invited by relationship not being set to the family that invited them. (so links to other visitors in that household but no links to the originating family)

If visitor is old enough to 'can check-in' and another visitor is under the programmed aged, the adult visitor will receive a can check-in known relationship to another visitor within the originating family.

**Comment by dcs619** [comment]
Fixed in 4a668c2e6d9f101468220cc26cb2cf4193a715b8
