### ISSUE TITLE
Import fails on F1 user import if same username already exists in Rock 

### ISSUE THREAD

**Issue by bwitting** [NewSpring/Excavator#82]
Hey David, an import of F1 data will fail if a username being imported from F1 is the same as a user that already exists in Rock.  Can you catch the exception and skip that row?

> System.Data.Entity.Infrastructure.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> System.Data.Entity.Core.UpdateException: An error occurred while updating the entries. See the inner exception for details. ---> System.Data.SqlClient.SqlException: Cannot insert duplicate key row in object 'dbo.UserLogin' with unique index 'IX_UserName'. The duplicate key value is (bwitting).
> 
> The statement has been terminated.
> 
> at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
> 
>   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
> ...

**Comment by Sylhos** [comment]
Hello guys!  Does anyone have a fork for this workaround?  I am having the same duplicate issue.  Thanks for the assistance!

**Comment by dcs619** [comment]
@Sylhos This issue had two items: username and existing attribute.  Which one are you experiencing?

**Comment by Sylhos** [comment]
It was the existing attribute error.  sorry about that!
